# REQUESTS FILMES

###
GET http://localhost:3000/

###
GET http://localhost:3000/catalogo/listar-filme/60847528cd75e91510a13090

###
POST http://localhost:3000/catalogo/cadastrar-filme
Content-Type: application/json

{
    "titulo": "Toy Story",
    "status": "DISPONÍVEL",
    "descricao": "Toy Story",
    "duracao":"1H30M",
    "genero": "Animação"
  
}

###
DELETE http://localhost:3000/catalogo/excluir-filme/60847b581a8124355caaa301

###
PUT http://localhost:3000/catalogo/editar-filme/60847528cd75e91510a13090
Content-Type: application/json

{
    "titulo": "Crespúsculo",
    "status": "DISPONÍVEL",
    "descricao": "Crepúsculo",
    "duracao":"1H30M",
    "genero": "Romance"
  
}

# REQUESTS LOCAÇÃO

###
GET http://localhost:3000/catalogo/locacao

###
GET http://localhost:3000/catalogo/listar-locacao/6084790bb3dc7a1bc07959df


###
POST http://localhost:3000/catalogo/cadastrar-locacao
Content-Type: application/json

{
  "data": "2000/01/01",
  "cliente": "60875c5936e03c181c4ab838",
  "filme": "60847528cd75e91510a13090"
}

###
DELETE http://localhost:3000/catalogo/excluir-locacao/6084790bb3dc7a1bc07959df

###
PUT http://localhost:3000/catalogo/editar-locacao/6087693eccf36b3180093839
Content-Type: application/json

{
  "data": "2010/10/10",
  "cliente": "60875c5936e03c181c4ab838",
  "filme": "60847528cd75e91510a13090"
}

# REQUEST USUARIO


###
GET http://localhost:3000/catalogo/cliente

###
POST http://localhost:3000/catalogo/cadastrar-usuario
Content-Type: application/json

{
  "usuario": "admin1",
  "senha": "admin1"
}

# REQUEST FAVORITOS

###
POST http://localhost:3000/catalogo/cadastrar-favorito
Content-Type: application/json

{
  "filme": "60849dbf91a62c1d94ccb4e3",
  "cliente": "60875c5936e03c181c4ab838"
}

###
DELETE http://localhost:3000/catalogo/excluir-favorito?id=60875ea24ca0e825f422ebaa